### ISSUE TITLE
Error to build pgauditlogtofile

### ISSUE THREAD

**Issue by SamuelMolling** [fmbiete/pgauditlogtofile#10]
Hi, i'm having trouble making the make install of your extension on postgres 13, follow the error bellow:

[root@postgres13 pgauditlogtofile]# make install USE_PGXS=1
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o logtofile.o logtofile.c
logtofile.c:55:3: error: unknown type name ‘LWLock’
   LWLock *lock;
   ^
logtofile.c: In function ‘guc_assign_directory’:
logtofile.c:110:7: error: ‘UsedShmemSegAddr’ undeclared (first use in this function)
   if (UsedShmemSegAddr == NULL)
       ^
logtofile.c:110:7: note: each undeclared identifier is reported only once for each function it appears in
logtofile.c:114:5: error: incompatible type for argument 1 of ‘LWLockAcquire’
     LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:116:5: error: incompatible type for argument 1 of ‘LWLockRelease’
     LWLockRelease(pgaudit_log_shm->lock);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c: In function ‘guc_assign_filename’:
logtofile.c:125:7: error: ‘UsedShmemSegAddr’ undeclared (first use in this function)
   if (UsedShmemSegAddr == NULL)
       ^
logtofile.c:129:5: error: incompatible type for argument 1 of ‘LWLockAcquire’
     LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:131:5: error: incompatible type for argument 1 of ‘LWLockRelease’
     LWLockRelease(pgaudit_log_shm->lock);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c: In function ‘guc_assign_rotation_age’:
logtofile.c:152:7: error: ‘UsedShmemSegAddr’ undeclared (first use in this function)
   if (UsedShmemSegAddr == NULL)
       ^
logtofile.c:156:5: error: incompatible type for argument 1 of ‘LWLockAcquire’
     LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:158:5: error: incompatible type for argument 1 of ‘LWLockRelease’
     LWLockRelease(pgaudit_log_shm->lock);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c: In function ‘_PG_init’:
logtofile.c:189:3: warning: implicit declaration of function ‘RequestNamedLWLockTranche’ [-Wimplicit-function-declaration]
   RequestNamedLWLockTranche("pgauditlogtofile", 1);
   ^
logtofile.c: In function ‘pgauditlogtofile_shmem_startup’:
logtofile.c:221:5: warning: implicit declaration of function ‘GetNamedLWLockTranche’ [-Wimplicit-function-declaration]
     pgaudit_log_shm->lock = &(GetNamedLWLockTranche("pgauditlogtofile"))->lock;
     ^
logtofile.c:221:73: error: invalid type argument of ‘->’ (have ‘int’)
     pgaudit_log_shm->lock = &(GetNamedLWLockTranche("pgauditlogtofile"))->lock;
                                                                         ^
logtofile.c: In function ‘pgauditlogtofile_needs_rotate_file’:
logtofile.c:325:5: error: incompatible type for argument 1 of ‘LWLockAcquire’
     LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:327:5: error: incompatible type for argument 1 of ‘LWLockRelease’
     LWLockRelease(pgaudit_log_shm->lock);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c:340:5: error: incompatible type for argument 1 of ‘LWLockAcquire’
     LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:343:5: error: incompatible type for argument 1 of ‘LWLockRelease’
     LWLockRelease(pgaudit_log_shm->lock);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c: In function ‘pgauditlogtofile_open_file’:
logtofile.c:377:3: warning: implicit declaration of function ‘MakePGDirectory’ [-Wimplicit-function-declaration]
   (void)MakePGDirectory(guc_pgaudit_log_directory);
   ^
logtofile.c:384:3: error: incompatible type for argument 1 of ‘LWLockAcquire’
   LWLockAcquire(pgaudit_log_shm->lock, LW_SHARED);
   ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:406:3: error: incompatible type for argument 1 of ‘LWLockRelease’
   LWLockRelease(pgaudit_log_shm->lock);
   ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c: In function ‘pgauditlogtofile_calculate_filename’:
logtofile.c:420:3: error: incompatible type for argument 1 of ‘LWLockAcquire’
   LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
   ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:429:3: error: incompatible type for argument 1 of ‘LWLockRelease’
   LWLockRelease(pgaudit_log_shm->lock);
   ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
make: *** [logtofile.o] Error 1

**Comment by fmbiete** [comment]
Are you sure you have installed the devel package for your postgresql version?
I can build this extension against v11, v12 and v13 without issues

**Comment by SamuelMolling** [comment]
yes, I also use pgbackrest and it uses these packages

**Comment by fmbiete** [comment]
Can you describe your setup? How are you installing PostgreSQL so that I can try to reproduce your issue?

**Comment by SamuelMolling** [comment]
I have a postgresql on version 13, I use the CentOS 7 operating system.

[root@tst-v-psql-1p01 pgauditlogtofile]# rpm -qa | grep -i "postgre"
nri-postgresql-2.7.0-1.x86_64
rh-postgresql13-postgresql-13.1-1.el7.x86_64
postgresql-9.2.24-6.el7_9.x86_64
postgresql13-server-13.4-1PGDG.rhel7.x86_64
rh-postgresql13-postgresql-libs-13.1-1.el7.x86_64
rh-postgresql13-postgresql-server-13.1-1.el7.x86_64
postgresql-libs-9.2.24-6.el7_9.x86_64
postgresql-devel-9.2.24-6.el7_9.x86_64
postgresql13-13.4-1PGDG.rhel7.x86_64
postgresql13-contrib-13.4-1PGDG.rhel7.x86_64
rh-postgresql13-runtime-3.7-1.el7.x86_64
postgresql13-libs-13.4-1PGDG.rhel7.x86_64
postgresql13-devel-13.4-1PGDG.rhel7.x86_64

[root@tst-v-psql-1p01 pgauditlogtofile]# make install USE_PGXS=1
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o logtofile.o logtofile.c
logtofile.c:55:3: error: unknown type name ‘LWLock’
   LWLock *lock;
   ^
logtofile.c: In function ‘guc_assign_directory’:
logtofile.c:110:7: error: ‘UsedShmemSegAddr’ undeclared (first use in this function)
   if (UsedShmemSegAddr == NULL)
       ^
logtofile.c:110:7: note: each undeclared identifier is reported only once for each function it appears in
logtofile.c:114:5: error: incompatible type for argument 1 of ‘LWLockAcquire’
     LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:116:5: error: incompatible type for argument 1 of ‘LWLockRelease’
     LWLockRelease(pgaudit_log_shm->lock);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c: In function ‘guc_assign_filename’:
logtofile.c:125:7: error: ‘UsedShmemSegAddr’ undeclared (first use in this function)
   if (UsedShmemSegAddr == NULL)
       ^
logtofile.c:129:5: error: incompatible type for argument 1 of ‘LWLockAcquire’
     LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:131:5: error: incompatible type for argument 1 of ‘LWLockRelease’
     LWLockRelease(pgaudit_log_shm->lock);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c: In function ‘guc_assign_rotation_age’:
logtofile.c:152:7: error: ‘UsedShmemSegAddr’ undeclared (first use in this function)
   if (UsedShmemSegAddr == NULL)
       ^
logtofile.c:156:5: error: incompatible type for argument 1 of ‘LWLockAcquire’
     LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:158:5: error: incompatible type for argument 1 of ‘LWLockRelease’
     LWLockRelease(pgaudit_log_shm->lock);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c: In function ‘_PG_init’:
logtofile.c:189:3: warning: implicit declaration of function ‘RequestNamedLWLockTranche’ [-Wimplicit-function-declaration]
   RequestNamedLWLockTranche("pgauditlogtofile", 1);
   ^
logtofile.c: In function ‘pgauditlogtofile_shmem_startup’:
logtofile.c:221:5: warning: implicit declaration of function ‘GetNamedLWLockTranche’ [-Wimplicit-function-declaration]
     pgaudit_log_shm->lock = &(GetNamedLWLockTranche("pgauditlogtofile"))->lock;
     ^
logtofile.c:221:73: error: invalid type argument of ‘->’ (have ‘int’)
     pgaudit_log_shm->lock = &(GetNamedLWLockTranche("pgauditlogtofile"))->lock;
                                                                         ^
logtofile.c: In function ‘pgauditlogtofile_needs_rotate_file’:
logtofile.c:325:5: error: incompatible type for argument 1 of ‘LWLockAcquire’
     LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:327:5: error: incompatible type for argument 1 of ‘LWLockRelease’
     LWLockRelease(pgaudit_log_shm->lock);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c:340:5: error: incompatible type for argument 1 of ‘LWLockAcquire’
     LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:343:5: error: incompatible type for argument 1 of ‘LWLockRelease’
     LWLockRelease(pgaudit_log_shm->lock);
     ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c: In function ‘pgauditlogtofile_open_file’:
logtofile.c:377:3: warning: implicit declaration of function ‘MakePGDirectory’ [-Wimplicit-function-declaration]
   (void)MakePGDirectory(guc_pgaudit_log_directory);
   ^
logtofile.c:384:3: error: incompatible type for argument 1 of ‘LWLockAcquire’
   LWLockAcquire(pgaudit_log_shm->lock, LW_SHARED);
   ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:406:3: error: incompatible type for argument 1 of ‘LWLockRelease’
   LWLockRelease(pgaudit_log_shm->lock);
   ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
logtofile.c: In function ‘pgauditlogtofile_calculate_filename’:
logtofile.c:420:3: error: incompatible type for argument 1 of ‘LWLockAcquire’
   LWLockAcquire(pgaudit_log_shm->lock, LW_EXCLUSIVE);
   ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:109:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockAcquire(LWLockId lockid, LWLockMode mode);
             ^
logtofile.c:429:3: error: incompatible type for argument 1 of ‘LWLockRelease’
   LWLockRelease(pgaudit_log_shm->lock);
   ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/storage/proc.h:20,
                 from logtofile.c:21:
/usr/include/pgsql/server/storage/lwlock.h:112:13: note: expected ‘LWLockId’ but argument is of type ‘int *’
 extern void LWLockRelease(LWLockId lockid);
             ^
make: *** [logtofile.o] Error 1

**Comment by fmbiete** [comment]
Take a look at your setup. You have 2 different versions of PostgreSQL installed 9.2.24 and 13.4.
The includes you are referencing are the ones from 9.2
You will have to adjust your environments variables or the makefile to use only 13.4... but I would recommend removing any package for 9.2.24

This extension supports v11, 12, 13... but not 9.x or 10
