### ISSUE TITLE
Multiple hooks can write to the auditlog at the same time

### ISSUE THREAD

**Issue by mvisserggd** [fmbiete/pgauditlogtofile#11]
First, thank you for providing this package.

I do seem to have an issue with it however.

If I check my log files it seems that hooks called at the same time, especially with larger logs can cause issues where logs get mixed up. I think it has to do with https://github.com/fmbiete/pgauditlogtofile/blob/master/logtofile.c#L443. It seems that fwrite is used without actually locking the file which can cause the same file to be written to simultaneously by multiple calls of the hook. I might be wrong, but it is a good guess I think.

Here is an example from a part of our logs:
```
... ... ... start of a log. Omitted because it's very large and not necessary 
union all
    (
    select D.xmin as last_tx
      from pg_catalog.pg_description D
        join pg_catalog.pg_operator O on O.oid = D.objoid
      where O.oprnamespace = $20::oid
        order by pg_catalog.age(D.xmin)
        limit 1
    )
2021-07-01 14:18:28.631 CEST,"user","database",61836,"localhost:47936",60ddb280.f18c,19,"SHOW",2021-07-01 14:18:08 CEST,2/73199,0,00000,"AUDIT: SESSION,18,1,MISC,SHOW,,,SHOW TRANSACTION ISOLATION LEVEL,<none>",,,,,,,,"log_audit_event, pgaudit.c:748","PostgreSQL JDBC Driver"
    union all
    (
    select D.xmin as last_tx
      from pg_catalog.pg_description D
        join pg_catalog.pg_collation C on C.oid = D.objoid
      where C.collnamespace = $21::oid
        order by pg_catalog.age(D.xmin)
        limit 1
    )

  ) X
  order by pg_catalog.age(X.last_tx)
  limit 1
) C, sa SA"",""101694651,101694651,153838,153838,153838,153838,153838,153838,153838,153838,153838,153838,153838,153838,153838,153838,153838,153838,153838,153838,153838""",,,,,,,,"log_audit_event, pgaudit.c:748","PostgreSQL JDBC Driver"
```

As you can see, a log is written with timestamp 2021-07-01 14:18:28.631 CEST in between the union statement. The union statement is actually quite large... using about 250 rows in the log file.
The timestamp of the union statement itself is also 2021-07-01 14:18:28.631 CEST so it seems they were called at exactly the same time, causing this issue. We have a very high-volume DB.

**Comment by fmbiete** [comment]
I think the issue is that we are using a file buffered by end line.
You could try commenting this line:
https://github.com/fmbiete/pgauditlogtofile/blob/master/logtofile.c#L391

And see if your issue goes away. But you could also see a higher number of iops caused by the audit

**Comment by mvisserggd** [comment]
@fmbiete sorry for the late reply.
It seems your latest changes fixed the issue for me. Thanks for that.

It might be a good idea to trigger an update on pkgs.org for the production installations.

Thanks for the support.
