### ISSUE TITLE
Question: does pgauditlogtofile work on Windows?

### ISSUE THREAD

**Issue by BillSmith-EDB** [fmbiete/pgauditlogtofile#14]
Does anyone know if this extension has been testing and is known to work on Windows?

**Comment by fmbiete** [comment]
I haven't tested on Windows, but I don't see why it shouldn't build and work there. It doesn't use anything Unix specific.
If you tested, please confirm if it works for you.

**Comment by harukat** [comment]
I successfully built pgauditlogtofie 1.5.12 by MSVC for the EDB PostgreSQL 15 binary on Windows with pgaudit 1.7.0, but the following modifications were required to avoid a crash on its loading.

```
diff --git a/logtofile.c b/logtofile.c
index bea73e1..53dcf46 100644
--- a/logtofile.c
+++ b/logtofile.c
@@ -159,7 +159,7 @@ static bool pgauditlogtofile_write_audit(const ErrorData *edata, int exclude_nch


 static void pgauditlogtofile_request_rotation(void) {
-  if (UsedShmemSegAddr == NULL)
+  if (UsedShmemSegAddr == NULL || pgaudit_log_shm == NULL )
        return;

   /* Directory is changed force a rotation */
```
