### ISSUE TITLE
File rotation is not working

### ISSUE THREAD

**Issue by rafapaisley** [fmbiete/pgauditlogtofile#19]
I have set the rotation with "set command" not by adding it to the config file.

postgres=# show pgaudit.log_rotation_age;
 pgaudit.log_rotation_age
--------------------------
 1d
(1 row)

Despite the rotation_age being set to 1d, the file contains data since i enabled audit ( a week ago )

**Comment by fmbiete** [comment]
You are using the wrong value
```
postgres=# select setting, name, unit from pg_settings where name like 'pgaudit.log_rotation_age';
 setting |           name           | unit 
---------+--------------------------+------
 1       | pgaudit.log_rotation_age | min
```

log_rotation_age unit is minutes. If you want to rotate after 1 day, you need to use pgaudit.log_rotation_age = 1440
