### ISSUE TITLE
pgaudit.log_connections does not work in postgresql version 14

### ISSUE THREAD

**Issue by fgrandvarlet** [fmbiete/pgauditlogtofile#22]
Hello,

I see a difference in behavior between postgresql 13 and postgresql 14 versions regarding connection/disconnection auditing:
Indeed it seems that the pgaudit.log_connections and pgaudit.log_disconnections parameters are not operational in version 14:
I created 2 instances, one in version 13, the other in version 14 with the following settings:

shared_preload_libraries = passwordcheck, pgaudit, pgauditlogtofile
pgaudit.log_directory = '../pg_log'
pgaudit.log_filename = 'audit-%Y%m%d.log'
pgaudit.log = 'ddl';
create database fgr;
\c fgr
create extension pgaudit;
create extension pgauditlogtofile;

When I create objects in the database, these actions are well audited in both cases.
However in version 14, connections and disconnections are also logged while the pgaudit.log_connections and pgaudit.log_disconnections parameters are set to off.
This is problematic in relation to the volume of logs generated.

**Comment by fmbiete** [comment]
```
pgaudit.log_connections / pgaudit.log_disconnections = off
```
are honoured now.

But you will see the connections/disconnections messages in your standard PostgreSQL log if you have the globals
```
log_connections / log_disconnections = on
```

Remember to disable also those if you want to save space.

**Comment by fgrandvarlet** [comment]
Thank you very much for taking this problem into account and for fixing it.
