### ISSUE TITLE
unable to restart a db when log_rotation_age = 0 

### ISSUE THREAD

**Issue by mattnspa** [fmbiete/pgauditlogtofile#24]
When I use 
```
ALTER` SYSTEM SET pgaudit.log_rotation_age = 0;
SELECT pg_reload_conf();
```
my settings are used. But if I restart my database using `systemctl restart postgresql-14` or `docker restart <postgres-container>` (on linux 8) the Postgres service fails to start.

journalctl logs:
```
Oct 28  postmaster[207313] LOG:  pgaudit extension initialized
Oct 28  kernel: traps: postmaster[207313] trap divide error ip:7f6e2e501d7f sp:7ffd8ba22160 error:0 in pgauditlogtofile.so[7f6e2e500000+4000]
```

using 
- Postgres:14.2
- pgaudit 1.6.2
- pgauditlogtofile 1.5.6

n.b this doesn't occur when running the docker container on MacOS.

**Comment by fmbiete** [comment]
I imagine you are using pgaudit.log_rotation_age = 0 with a daily file.
The fix committed should solve the issue. There will be no rotation though, so make sure to adjust your log filename pattern for your needs and monitor its size.
