### ISSUE TITLE
pgauditlogtofile only works with lc_messages set to en_US

### ISSUE THREAD

**Issue by hubiongithub** [fmbiete/pgauditlogtofile#25]
Hello

logtofile sets some strings like
static const char * pgAuditLogToFileDisconnPrefixes[] = {
  "disconnection: session time:",
};

Is there a chance to generate the suitable strings from the postgresql sources instead of hardcoding each language?

Nice tool nevertheless

**Comment by fmbiete** [comment]
Yes, this is missing, I'll try to add it when I have some time

**Comment by fmbiete** [comment]
That commit should implement the support for NLS and allow to filter the messages in a better way.
If you can test and confirm if this solve the issue for you it would be awesome.

**Comment by hubiongithub** [comment]
Hello Francisco
I can try to build it (we normally use packages delivered by apt/yum.postgresql.org).
What requirements (beside the obvious "make") do we need?

**Comment by fmbiete** [comment]
Something like this would be enough
```
dnf install postgresql15-server postgresql15-devel gcc make openssl-devel

make clean
make install
```

**Comment by hubiongithub** [comment]
On Ubuntu it needed:
apt install postgresql-server-dev-<version you need> # which installs all the tools needed to compile as dependencies
apt install libkrb5-dev zlib1g-dev

**Comment by hubiongithub** [comment]
Hello Francisco

On Ubuntu it needed 
apt install postgresql-server-dev-<version you want to compile for>  # which dependencies also install compiler ...
apt install libkrb5-dev zlib1g-dev

make USE_PGXS=1
I copied the created pgauditlogtofile.so to /usr/lib/postgresql/<version>/lib/pgauditlogtofile.so to test it with
- lc_messages = 'en_US.UTF-8'                     # still works
- lc_messages = 'de_DE.UTF-8'                     # now send the german messages to the correct logfile

At least for the german settings it works.
