### ISSUE TITLE
pgauditlogtofile extension log formatting and Fluent-Bit parsing

### ISSUE THREAD

**Issue by valterartur** [fmbiete/pgauditlogtofile#27]
Hello,

I'm using your pgauditlogtofile extension for PostgreSQL to generate audit logs. Recently, I was trying to send these logs to Logstash using Fluent-Bit, and I encountered an issue with multiline logs.

The pgaudit logs have a specific format, and I noticed that changes to the log_line_prefix are not being reflected in the logs generated by pgauditlogtofile extension. It appears that the pgauditlogtofile extension might have its own log format which I could not find detailed in the documentation.

This has caused some parsing issues in Fluent-Bit, especially with multiline logs. My main interest lies in parsing the user, database, and the query that was run.

Here is an example of the logs:
```
2023-07-24 21:45:50.183 UTC,postgres(user?),postgres(pwd?),2123,[local],64bef10e.84b,1,SELECT,2023-07-24 21:45:50 UTC,3/1192,0,00000,SESSION,1,1,READ,SELECT,,,"select application_name, sync_state from pg_stat_replication",<not logged>,,,,,,,,,
```
while the default format of pgaudit is
```
AUDIT: SESSION,36,1,DDL,ALTER TABLE,TABLE,public.test2,ALTER TABLE test RENAME TO test2,<not logged>
```
versions
```
ENV PG_VERSION 13.7
ENV PGAUDIT_VERSION 1.5.2
ENV PGAUDITLOGTOFILE_VERSION 1.5.12
```
Can you please clarify:
1. What is the exact format of the logs generated by the pgauditlogtofile extension?
2. Is it possible to customize the log format to specifically highlight the user, database, and the query?
3. Could you provide any advice or best practices on how to parse these logs with Fluent-Bit  (or any regex)?
Any guidance would be greatly appreciated.

**Comment by fmbiete** [comment]
The format is fixed and in CSV format:
```
datetime,user_name,database_name,pid,remote_host,remote_port,session_id,line_number,ps_display,session_start_datetime,virtual_transaction_id,transaction_id,sql_state_code,pgaudit log line (AUDIT: removed),detail,hint,internalquery,internalpos,context,debug_query_string,cursorpos,funcname,filename_linenum,application_name
```

So if you want, you can extract from that line the pgaudit log message (minus the AUDIT: )

No, it's not possible to customize the log format. We are showing all the information available in postgres, anyone can decide to ignore what they don't need (btw, the longest part is the pgaudit message, which would not make sense to ignore either way).

pgaudit returns the statements as multi-line strings. 
A way of manually parsing this file (or pgaudit) would be:
each line starting with a datetime and a comma marks the start the of a new record
you read lines until you find a new line that matches the above, all the above is part of the same record

Or you could try to find a good CSV library that supports multi-lines fields. The statements are quote enclosed, so this should be a valid multi-line CSV

**Comment by valterartur** [comment]
@fmbiete Thank you for your detailed response. It's been very helpful in understanding the structure of the logs. However, I've noticed a discrepancy when comparing my logs to the format you've provided.

In my log lines, it seems like I only have 30 fields instead of the 32 as outlined.

Here's an example log entry:
```
2023-07-27 08:27:27.465 UTC,postgres,postgres,408,[ip:port],64c22806.198,135,BIND,2023-07-27 08:17:10 UTC,9/61,0,00000,SESSION,135,1,READ,SELECT,,,SELECT 1,<not logged>,,,,,,,,,PostgreSQL JDBC Driver
```
And this is how I've mapped it:
```
datetime - 2023-07-27 08:27:27.465 UTC
user_name - postgres
database_name - postgres
pid - 2680
remote_host - [ip:port]
remote_port - ? (Seems to be included in remote_host)
session_id - 64c22806.198
line_number - 135
ps_display - BIND
session_start_datetime - 2023-07-27 08:17:10 UTC
virtual_transaction_id - 9/61
transaction_id - 0
sql_state_code - 00000
# pgaudit log line (AUDIT: removed) - the next 9 entries are from pgaudit
audit_type - SESSION 
statement_id - 135
substatement_id - 1
class - READ
command - SELECT
object_type - ""
object_name - ""
statement - "SELECT 1"
parameter - <not logged>
detail - ""
hint - ""
internalquery - ""
internalpos - ""
context - ""
debug_query_string - ""
cursorpos - ""
funcname - ""
filename_linenum - ? (Seems to be missing)
application_name - "PostgreSQL JDBC Driver"
```
The remote_port appears to be included in the remote_host field as [ip:port]. Is this a possible configuration or version difference?

Additionally, the filename_linenum (or some of the last) seems missing from my logs. Could you advise please?


Here is my current working fluent bit parser for version 2.1
```
  parsers.conf: |-
    [MULTILINE_PARSER]
      name          pgaudit_multiline
      type          regex
      flush_timeout 500
  
      rule         "start_state"   "/(^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} UTC,)(.*)/"  "cont"
      rule         "cont"          "/^(?!\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} UTC,).*/"  "cont"
    
    [PARSER]
      Name        pgaudit_parser
      Format      regex
      Regex       /^(?<timestamp>[^,]+),(?<user>[^,]+),(?<db>[^,]+),(?<pid>[^,]*),(?<client>[^,]*),(?<session_id>[^,]*),(?<arg_1>[^,]*),(?<cmd>[^,]*),(?<query_ts>[^,]*),(?<arg_2>[^,]*),(?<arg_3>[^,]*),(?<arg_4>[^,]*),(?<action>[^,]*),(?<arg_5>[^,]*),(?<arg_6>[^,]*),(?<arg_7>[^,]*),(?<arg_8>[^,]*),(?<arg_9>[^,]*),(?<arg_10>[^,]*),(?<query>(?<=,")[^"]*(?=",)|(?<=,)[^,]*),(?<arg_11>[^,]*),(?<arg_12>[^,]*),(?<arg_13>[^,]*),(?<arg_14>[^,]*),(?<arg_15>[^,]*),(?<arg_16>[^,]*),(?<arg_17>[^,]*),(?<arg_18>[^,]*),(?<arg_19>[^,]*),(?<application>.*)$/
      Time_Key    timestamp
      Time_Format %Y-%m-%d %H:%M:%S.%L %Z
```
Just before cleaning it out want to know if there are other useful parameters.

**Comment by fmbiete** [comment]
That looks correct to me.
_port_ will be present if it's a remote/TCP connection
_filename_linenum_ will only be present if we have those values (I think to remember it was with debug builds)
