### ISSUE TITLE
Misplaced rotate

### ISSUE THREAD

**Issue by jiangshuai1995** [fmbiete/pgauditlogtofile#28]
I set pgaudit.log_rotation_age = 0 ,Because I want to use the system's logrotate

but not disable the rotation
```
[local]:5432 postgres@postgres=# show pgaudit.log_rotation_age ;
 pgaudit.log_rotation_age
--------------------------
 0
(1 row)
```

When a new connection is established, a new file is still created, although this is not necessarily referred to as a rotation

```
[root@test-dts log]# ll
-rw------- 1 postgres postgres   694 8月  15 16:56 audit-20230815_1656.log
-rw------- 1 postgres postgres   878 8月  15 16:58 audit-20230815_1658.log
-rw------- 1 postgres postgres  8506 8月  15 17:00 audit-20230815_1659.log
-rw------- 1 postgres postgres 16671 8月  15 17:07 audit-20230815_1700.log
-rw------- 1 postgres postgres  3015 8月  15 17:03 audit-20230815_1702.log
-rw------- 1 postgres postgres  4120 8月  15 17:07 audit-20230815_1707.log
-rw------- 1 postgres postgres   347 8月  15 17:09 audit-20230815_1709.log
-rw------- 1 postgres postgres   333 8月  15 17:12 audit-20230815_1712.log
```

**And**
Undisconnected connections are still writing old log files
For example, logfile  *audit-20230815_1700.log*  , which is still changing at time *17:07*

**Comment by jiangshuai1995** [comment]
postgres version 13.9 
main branch compiler

**Comment by fmbiete** [comment]
What you are trying to do is not possible.

You need to specify a log_rotation_age greater than 0 (that you can set 0 is a bug to fix).

Each postgres process will open the audit file and write to it. 
Every time there is some activity, that process will check if it needs to rotate the file (close the current one and open a new one).

If a postgres process doesn't have any activity, it will keep the last audit file that it has used open.
I'm trying to find a way to report to all the backends the rotation, but it doesn't seem easy (if you know of a way, please let me know).

if you did the rotation externally we should need a mechanism to inform postgres to reopen the file, which would be again the same problem as above.

**Comment by jiangshuai1995** [comment]
I quite agree with you.
It seems difficult to solve this problem with extension. I have no good ideas.
Thanks for your reply, if you want you can close this issue anytime.

**Comment by fmbiete** [comment]
Take a look at branch _next_. We are using a background worker to calculate the file to use, which should fix your issue.
There is also a new experimental option to automatically close an audit log file after some inactivity period.
