### ISSUE TITLE
COPY postgres_log FROM '/full/path/to/logfile.csv' WITH csv;  

### ISSUE THREAD

**Issue by bagafoot** [fmbiete/pgauditlogtofile#3]
Hi all,
I've got postgresql_log table from this docs postgresql. 
https://www.postgresql.org/docs/current/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-CSVLOG

and I want to copy all postgres csv logs in this table, both postgresql-X.csv and audit-X.log,  but audit.log incompatible with postgresql_log table amd I get this error. 
`ERROR:  missing data for column "application_name"`

My pg loggings are 
![logsettings](https://user-images.githubusercontent.com/30403489/89542884-ed40b400-d808-11ea-9275-8c1594e03f75.PNG)

When drop the pgauditlogtofile extension, audit log fit well.
Can you help me how to fit audit log postgres_log table.

example row postgres csv log: 
2020-08-06 09:30:42.379 +03,"test.user","adb",2474,"[local]",5f2ba353.9aa,10,"idle",2020-08-06 09:29:39 +03,3/33,0,LOG,00000,"statement: select a.id as aid, d.id as did from adb_sch.aaa a join adb_sch.ddd d on a.id=d.id;",,,,,,,,,"psql"

audit log: 
2020-08-06 09:36:24.644 +03,"test.user","adb",2891,"[local]",5f2ba4e7.b4b,1,"SELECT",2020-08-06 09:36:23 +03,3/13,0,00000,"AUDIT: SESSION,1,1,READ,SELECT,,,""select a.id as aid, d.id as did from adb_sch.aaa a join adb_sch.ddd d on a
    .id=d.id;"",<not logged>",,,,,,,,,"psql"

**Comment by fmbiete** [comment]
Hi @bagafoot 

Take a look at your example lines, they don't have the same fields ("idle" vs "SELECT", LOG vs "AUDIT: SESSION,1,1,READ,SELECT,,,"...). As they are, you need a different table format; both have the same fields up to virtual_transaction_id. But after that one you will have to define different columns and types.

**Comment by bagafoot** [comment]
Thanks a lot @fmbiete 
Can you help which columns should be in table because I don't know what refer to this commas in a row. ( .id;"","**,,,,,,,,,**"psql")

**Comment by fmbiete** [comment]
Take a look at [pgaudit Format section](https://github.com/pgaudit/pgaudit#format)

**Comment by bagafoot** [comment]
thanks a lot

**Comment by Linour** [comment]
@bagafoot hey can I ask how you structured the table after looking at [pgaudit Format section](https://github.com/pgaudit/pgaudit#format) ? I'm also trying to enter the logs into a table.

**Comment by bagafoot** [comment]
> @bagafoot hey can I ask how you structured the table after looking at [pgaudit Format section](https://github.com/pgaudit/pgaudit#format) ? I'm also trying to enter the logs into a table.
@Linour 

CREATE FOREIGN TABLE public.pglog (
	log_time timestamptz(3) NULL,
	user_name text NULL,
	database_name text NULL,
	process_id int4 NULL,
	connection_from text NULL,
	session_id text NULL,
	session_line_num int8 NULL,
	command_tag text NULL,
	session_start_time timestamptz NULL,
	virtual_transaction_id text NULL,
	transaction_id int8 NULL,
	error_severity text NULL,
	sql_state_code text NULL,
	message text NULL,
	detail text NULL,
	hint text NULL,
	internal_query text NULL,
	internal_query_pos int4 NULL,
	context text NULL,
	query text NULL,
	query_pos int4 NULL,
	"location" text NULL,
	application_name text NULL
)
SERVER pglog
OPTIONS (filename '/pg12/mounts/pg_log/log.csv', format 'csv');
