### ISSUE TITLE
warning: assignment discards ‘const’ qualifier from pointer target type

### ISSUE THREAD

**Issue by vincedau** [fmbiete/pgauditlogtofile#34]
Hello,

Is it only a warning and will pgauditlogtofile works whitout error ?
How to correct it ( if possible ) ?

Thanks for your answer.

Regards

 gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fPIC -I. -I./ -I/soft/postgresql-15.2/pgsql/include/server -I/soft/postgresql-15.2/pgsql/include/internal  -D_GNU_SOURCE   -c -o logtofile.o logtofile.c
logtofile.c: In function ‘pgauditlogtofile_unique_prefixes’:
logtofile.c:357:15: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       message = messages[i];
               ^

**Comment by fmbiete** [comment]
Sorry for the delayed response.

Are you sure you are using the latest version?
I don't have that warning while using _-Wdiscarded-qualifiers_ and the line 357 doesn't include a reference to _message_, plus the _const_ for _message_ was removed some commits back:
```
          if (is_unique) {
```

**Comment by suveshmathur** [comment]
I'm also seeing the identical error in latest version pgauditlogtofile-1.5.12 (pgauditlogtofile-1.5.12.tar.gz) on RedHat 8.8

 make install USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC -I. -I./ -I/home/postgres/pgsql-14/include/server -I/home/postgres/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pgauditlogtofile.o pgauditlogtofile.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC -I. -I./ -I/home/postgres/pgsql-14/include/server -I/home/postgres/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2   -c -o logtofile.o logtofile.c
logtofile.c: In function ‘pgauditlogtofile_unique_prefixes’:
logtofile.c:356:15: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       message = messages[i];
               ^
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC -shared -o pgauditlogtofile.so pgauditlogtofile.o logtofile.o -lz -L/home/postgres/pgsql-14/lib   -Wl,--as-needed -Wl,-rpath,'/home/postgres/pgsql-14/lib',--enable-new-dtags
/usr/bin/mkdir -p '/home/postgres/pgsql-14/lib'
/usr/bin/mkdir -p '/home/postgres/pgsql-14/share/extension'
/usr/bin/mkdir -p '/home/postgres/pgsql-14/share/extension'
/usr/bin/install -c -m 755  pgauditlogtofile.so '/home/postgres/pgsql-14/lib/pgauditlogtofile.so'
/usr/bin/install -c -m 644 .//pgauditlogtofile.control '/home/postgres/pgsql-14/share/extension/'
/usr/bin/install -c -m 644 .//pgauditlogtofile--1.0.sql .//pgauditlogtofile--1.0--1.2.sql .//pgauditlogtofile--1.2--1.3.sql .//pgauditlogtofile--1.3--1.4.sql .//pgauditlogtofile--1.4--1.5.sql  '/home/postgres/pgsql-14/share/extension/'

**Comment by fmbiete** [comment]
Thank your for that information, this warning should be fixed in the related commit.

One thing to pay attention is that you were getting that warning in the fallback flow if your system doesn't have gettext (translation are not available to PostgreSQL). You could want into this, or maybe you are running in a embedded/limited system with only the base language...
