### ISSUE TITLE
Is it possible to describe audit log record's field?

### ISSUE THREAD

**Issue by Simurgl** [fmbiete/pgauditlogtofile#39]
Found that audit log file record structure is different from generated by pure pgaudit extension.
Is that possible to describe fields of records, generated by pgauditlogtofile extension? 
Part of them I have identified already, but some of them still are unclear.
As example, here is record, generated by insert into test database's test table by postgres user:

2024-06-05 15:56:34.521 EEST,postgres,test,6106,[local],66606022.17da,1,INSERT,2024-06-05 15:54:58 EEST,9/323,0,00000,SESSION,1,1,WRITE,INSERT,,,"insert into test values(4,'test');",<not logged>,,,,,,,,,psql

So, as I understood, 

2024-06-05 15:56:34.521 EEST --- log time
postgres  --- username
test  --- database name
6106 --- PID
[local] --- host name
66606022.17da     ---- UNCLEAR
1  --- statement id
INSERT  ---- command
2024-06-05 15:54:58 EEST   ---- SQL start time
9/323   ---- UNCLEAR
0          ---- UNCLEAR
00000  ---- UNCLEAR
SESSION  ---- AUDIT TYPE (SESSION or OBJECT)
1  --- STATEMENT ID
1 --- SUBSTATEMENT ID
WRITE   -- AUDIT CLASS, according to pgaudit.log values
INSERT  --- COMMAND
null              ----- OBJECT TYPE (if AUDIT TYPE is OBJECT)
null              ----- OBJECT NAME (if AUDIT TYPE is OBJECT)
"insert into test values(4,'test');"  --- SQL text
<not logged>  --- parameter value, according to pgaudit.log_parameter value
null      ---- UNCLEAR    
null      ---- UNCLEAR
null      ---- UNCLEAR
null      ---- UNCLEAR
null      ---- UNCLEAR
null      ---- UNCLEAR
null      ---- UNCLEAR
psql   ---- used application 

Please, could you confirm that I have correctly understood known fields types and clarify those marked as UNCLEAR.

Thank you in advance.

**Comment by fmbiete** [comment]
Hi Simurgi, I have described the fields in the README

**Comment by Simurgl** [comment]
Thank you a lot! Have a great day!
