### ISSUE TITLE
undefined symbol: Log_error_verbosity

### ISSUE THREAD

**Issue by 1schmnkS** [fmbiete/pgauditlogtofile#40]
Hello, 

postgres 16
os: rhel 9

I installed pgauditlogtofile_16 from the pgdg repos. After adding pauditlogtofile to shared_preload_libraries I stopped the cluster. On startup I ran into the following error: 

time=2024-06-26 11:53:42 CEST, pid=141962 FATAL:  could not load library "/usr/pgsql-16/lib/pgauditlogtofile.so": /usr/pgsql-16/lib/pgauditlogtofile.so: undefined symbol: Log_error_verbosity

do you have any hints what I might have done wrong? 

Thanks & KR

**Comment by fmbiete** [comment]
I don't manage the builds from PGDG, but I have tried to install those packages in a new docker container based in RHEL 9 and I don't see any issue.
Log_error_verbosity is defined in PostgreSQL main project. I would suspect your setup has something wrong and maybe "dnf reinstall" would help.

```
pgaudit_16-16.0-1PGDG.rhel9.x86_64
pgauditlogtofile_16-1.6.0-1PGDG.rhel9.x86_64
pgdg-redhat-repo-42.0-42PGDG.noarch
postgresql16-16.3-1PGDG.rhel9.x86_64
postgresql16-libs-16.3-1PGDG.rhel9.x86_64
postgresql16-server-16.3-1PGDG.rhel9.x86_64
```

```
shared_preload_libraries = 'pgaudit,pgauditlogtofile'
```

```
2024-06-27 10:37:52.122 UTC [185] LOG:  pgauditlogtofile worker started
```

If you can replicate your issue in a clean server/container, indicate the steps you are following.
