### ISSUE TITLE
pgauditlogtofile - the log file does not rotate

### ISSUE THREAD

**Issue by jiri-navratil-rb** [fmbiete/pgauditlogtofile#47]
Hi,

I want to use pgaudit and pgauditlogtofile in our environment, but I encountered a problem where the audit log files are not rotated. I need the file to rotate after 24 hours, but the rotation does not occur and the audit logs are still saved to the file that was created when pgaudit/pgauditlogtofile was initially configured/run. The audit log is still written to this file after the Postgres database is restarted or even after pgaudit/pgauditlogtofile is deconfigured and reconfigured. Even in the situation when I stop the database and delete this log file, the file with the same name (as it had when pgaudit/pgauditlogtofile was initially initialized) is re-created and the audit logs continue to be written to it. I have also tried shortening pgaudit.log_rotation_age to 3 minutes and the situation is still the same. Can you give me any advice on where the problem might be, I am attaching the configuration.
Thanks

Environment configuration:
I'm trying this on two database versions 13 and 16

Postgres version 16.4
pgaudit_16.x86_64                             16.0-1PGDG.rhel8
pgauditlogtofile_16.x86_64                    1.6.0-1PGDG.rhel8

Postgres version 13.14
pgaudit15_13.x86_64                           1.5.2-1.rhel8
pgauditlogtofile_13.x86_64                    1.6.0-1PGDG.rhel8

Konfiguration  postgres.conf  - same for Postgres 16 and 13
pgaudit.log = 'function,role,ddl,misc,misc_set'
pgaudit.log_catalog=off
pgaudit.log_directory='/pgfra01/ABC1xxS1PG/audit'
pgaudit.log_filename='audit-%Y%m%d_%H%M.log'
pgaudit.log_rotation_age=1440
pgaudit.log_connections=on
pgaudit.log_disconnections=on

**Comment by thomashelgi** [comment]
Hi,

I have a same/similar problem in my works environment where we want to use pgaudit og pgauditlogtofile and the logfile does not rotate. 
We are using Postgres v.15 on RHEL 8 with those extensions. 
My config looks like this
pgaudit.log_filename='pgaudit-%a.csv'
pgaudit.log='all,-misc'
pgaudit.log_directory='audit'
pgaudit.log_connections=on
pgaudit.log_disconnections=on
pgaudit.log_rotation_age=1d
pgaudit.log_truncate_on_rotation=on

**Comment by jiri-navratil-rb** [comment]
Hi,
in my case, the solution was to set the parameter max_worker_processes to a higher value. In my opinion, both pgaudit and pgauditlogtofile allocate one worker each. When you have another extension in the database, such as pg_cron, a low value of max_worker_processes means that there isn’t a free worker available for pgauditlogtofile, and the audit file rotation does not occur.
Regards

**Comment by thomashelgi** [comment]
Hi,
I added yesterday
`max_worker_processes = 20      `        
and it still does not rotate. We have also installed pg_cron on instance at my work however I experience the same thing on my test instance at home running inside a LXD container with only pgaudit and pgauditlogtofile extensions installed. The LXD container is running inside a 3CPU VM with access to all CPU's if necessary. 
The instance at work is running inside a 2CPU VM. 
Is there any other configuration in postgresql.conf that I'm missing ?

**Comment by fmbiete** [comment]
For the rotation to happen you need to make sure of 2 things:
- You have enough background workers (otherwise this extension and other postgres process will not run correctly)
- Your configuration is correctly set


_pg_audit.log_rotation_age_ should be specified in minutes
_pg_audit.log_truncate_on_rotation_ is not a valid setting

Check your server logs for errors, specially during postgres startup. If you don't have enough shared memory or enough background workers you could see messages related to that.
Check if the value _pg_audit.log_directory_ a partial path could be writing somewhere that is not where you are intending, that depends in other postgres startup variables. Use a full path if possible.
