### ISSUE TITLE
Deadlock Due to Shared prev_shmem_request_hook in PG15

### ISSUE THREAD

**Issue by guo-m-j** [fmbiete/pgauditlogtofile#49]
**Environment:**

PostgreSQL Version: 15.8
Plugins: pgaudit, pgauditlogtofile, pglogical
Description:
When attempting to start a PostgreSQL instance with the following configuration:
`shared_preload_libraries = 'pgaudit, pgauditlogtofile, pglogical' ` 
the instance fails to start due to an issue related to the prev_shmem_request_hook variable.

**Details:**
In both the pgauditlogtofile and pglogical plugins, the variable `prev_shmem_request_hook` is used across multiple files. Since this variable cannot be defined as static (to allow access from those files), it leads to potential name conflicts between plugins.

When the pgauditlogtofile plugin initializes, it stores the `prev_shmem_request_hook` pointer to the pglogical plugin hook, which means it first enters the pglogical plugin's hook function.

Upon entering the pglogical hook, the value of `prev_shmem_request_hook` still points to the pglogical function, leading to an infinite recursive call.
![image](https://github.com/user-attachments/assets/3c24eef9-65b2-48a8-8cca-a90242a5455a)

**Suggested Solution:**
To prevent this issue, I recommend renaming the `prev_shmem_request_hook` variable in both plugins by adding a unique prefix (e.g., `pgauditlogtofile_prev_shmem_request_hook` for the pgauditlogtofile plugin) to avoid naming conflicts. This change will ensure that each plugin manages its own hook without interfering with others, thereby preventing the deadlock from occurring.

**Comment by fmbiete** [comment]
Thank you for troubleshooting this, that should be fixed in the linked commit
