### ISSUE TITLE
ERROR:  parameter "pgaudit.log_directory" cannot be changed now

### ISSUE THREAD

**Issue by XABUNO** [fmbiete/pgauditlogtofile#5]
Hello,

I am getting this error saying 'ERROR:  parameter "pgaudit.log_directory" cannot be changed now' after I tried to set it to my desired audit path using the command "SET pgaudit.log_directory = '/usr/pgsql-11/audit';" at a line after the commands to set the original PGAudit parameters. Does anyone have a clue on this?

I am using Postgres 11, PGAudit 1.3.2, and pgauditlogtofile-11-1.0-1, running on RHEL 8.
The binary packages are retrieved from: 
https://centos.pkgs.org/8/postgresql-11-x86_64/pgauditlogtofile-11-1.0-1.rhel8.x86_64.rpm.html
https://centos.pkgs.org/8/postgresql-11-x86_64/pgaudit13_11-1.3.2-1.rhel8.x86_64.rpm.html

Thanks!

**Comment by fmbiete** [comment]
You should use something like this to modify system settings:

```
ALTER SYSTEM SET pgaudit.log_directory = '/usr/pgsql-11/audit';
SELECT pg_reload_conf();
```



`SET ...` will modify settings at the session level, and most of pgaudit settings are not modifiable at this scope

**Comment by XABUNO** [comment]
> You should use something like this to modify system settings:
> 
> ```
> ALTER SYSTEM SET pgaudit.log_directory = '/usr/pgsql-11/audit';
> SELECT pg_reload_conf();
> ```
> 
> `SET ...` will modify settings at the session level, and most of pgaudit settings are not modifiable at this scope

Thanks a lot! I know that SET works at the session level but I thought it's okay because some original pgaudit parameters like pgaudit.log work at the session level and I thought this parameter would work at that level too.

Do you mind adding this to README so it will be clearer to future users? Or maybe I can open a PR?

Thank you again for creating this awesome add-on and answering my question!
