### ISSUE TITLE
enhancement : add syslog option

### ISSUE THREAD

**Issue by dblugeon** [fmbiete/pgauditlogtofile#6]
Hello,
Is it possible to add options to your extension which permits to send auditlog to syslog ?

The need is to keep technical logs on the side (syslog or logfile), and send to another side the audit log in another syslog channel (with syslog options independent of the general postgresql configuration.

Thank you for your work.

**Comment by fmbiete** [comment]
It could be implemented, but that's not something I would use or even thinking of doing. 

syslog events should have a max length of 1024, that would force us to split the records, and potentially having out of order issues (head record 1, head record 2, record 2, record 1, record 2...)
You would end not being able to identify the whole record, unless we add always a header to each split part. It would make quite difficult the extraction of complete audit records.

**Comment by dblugeon** [comment]
Thanks you for your response.
I understand the max length problem of syslog event.
