### ISSUE TITLE
makePGDirectory is not available before PG11

### ISSUE THREAD

**Issue by dblugeon** [fmbiete/pgauditlogtofile#8]
Hello,
When I tried to use your extension PG10, I get the error "undefined Symbol: MakePGDirectory". This function is available only since PG11 (https://github.com/postgres/postgres/commit/da9b580d89903fee871cf54845ffa2b26bda2e11).

Affected version: 10 and probably 9.6.

**Comment by fmbiete** [comment]
Hi dblugeon,

Sorry, I didn't include support for PostgreSQL 10 or earlier since in my use case I'm not using those versions. If you are interested in them you could create a pull request 😄

**Comment by dblugeon** [comment]
Hello,
Sorry my absence and thank you for the patch.
